import React, { Fragment } from "react";
import AtomicElement from "./AtomicElement";
import "./Periodic.css";
const Periodic = (propos) => {
  const CATEGORIES = {
    Language: "alkali-metal",
    Devops: "alkaline-earth-metal",
    AgileMethod : "lanthanoid",
    Design: "actinoid",
    SoftSkills: "soft-skill",
    Basics: "transition-metal",
    Monitoring: "transition-monitoring",
    PostSoftSkills: "post-transition-metal",
    Management: "metalloid",
    Framework: "other-nonmetal",
    DataBase: "noble-gasse",
    ProgrammingLanguage: "unknown",
  };
  const ELEMENTS = [
    {
      category: CATEGORIES.Framework,
      symbol: "F",
      name: "Flutter",
      atomicMass: 1.008,
      atomicNumber: 1,
      atomicWeight: [1],
      column: 1,
      row: 1,
    },
    {
      category: CATEGORIES.DataBase,
      symbol: "SQL",
      name: "Sql",
      atomicMass: 4.0026,
      atomicNumber: 2,
      atomicWeight: [2],
      column: 18,
      row: 1,
    },
    {
      category: CATEGORIES.Language,
      symbol: "En",
      name: "English",
      atomicMass: 6.94,
      atomicNumber: 3,
      atomicWeight: [3],
      column: 1,
      row: 2,
    },
    {
      category: CATEGORIES.Devops,
      symbol: "Do",
      name: "Docker",
      atomicMass: 9.0122,
      atomicNumber: 4,
      atomicWeight: [2, 2],
      column: 2,
      row: 2,
    },
    {
      category: CATEGORIES.Management,
      symbol: "Ri",
      name: "Risk Management",
      atomicMass: 10.81,
      atomicNumber: 5,
      atomicWeight: [2, 3],
      column: 13,
      row: 2,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "Ex",
      name: "Express.Js",
      atomicMass: 12.011,
      atomicNumber: 6,
      atomicWeight: [2, 4],
      column: 14,
      row: 2,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "No",
      name: "Node.Js",
      atomicMass: 14.007,
      atomicNumber: 7,
      atomicWeight: [2, 5],
      column: 15,
      row: 2,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "Ne",
      name: "Nest.Js",
      atomicMass: 15.999,
      atomicNumber: 8,
      atomicWeight: [2, 6],
      column: 16,
      row: 2,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "Sp",
      name: "Spring",
      atomicMass: 18.998,
      atomicNumber: 9,
      atomicWeight: [2, 7],
      column: 17,
      row: 2,
    },
    {
      category: CATEGORIES.DataBase,
      symbol: "O",
      name: "Oracle",
      atomicMass: 20.18,
      atomicNumber: 10,
      atomicWeight: [2, 8],
      column: 18,
      row: 2,
    },
    {
      category: CATEGORIES.Language,
      symbol: "Fr",
      name: "Frensh",
      atomicMass: 22.99,
      atomicNumber: 11,
      atomicWeight: [2, 8, 1],
      column: 1,
      row: 3,
    },
    {
      category: CATEGORIES.Devops,
      symbol: "Gi",
      name: "Git",
      atomicMass: 24.305,
      atomicNumber: 12,
      atomicWeight: [2, 8, 2],
      column: 2,
      row: 3,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Al",
      name: "Aluminium",
      atomicMass: 26.982,
      atomicNumber: 13,
      atomicWeight: [2, 8, 3],
      column: 13,
      row: 3,
    },
    {
      category: CATEGORIES.Management,
      symbol: "Task",
      name: "Management",
      atomicMass: 28.085,
      atomicNumber: 14,
      atomicWeight: [2, 8, 4],
      column: 14,
      row: 3,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "Re",
      name: "React.Js",
      atomicMass: 30.974,
      atomicNumber: 15,
      atomicWeight: [2, 8, 5],
      column: 15,
      row: 3,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "A",
      name: "Angular",
      atomicMass: 32.06,
      atomicNumber: 16,
      atomicWeight: [2, 8, 6],
      column: 16,
      row: 3,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "Aj",
      name: "Angular.Js",
      atomicMass: 35.45,
      atomicNumber: 17,
      atomicWeight: [2, 8, 7],
      column: 17,
      row: 3,
    },
    {
      category: CATEGORIES.DataBase,
      symbol: "P",
      name: "PostgreSQL",
      atomicMass: 39.948,
      atomicNumber: 18,
      atomicWeight: [2, 8, 8],
      column: 18,
      row: 3,
    },
    {
      category: CATEGORIES.Language,
      symbol: "Ar",
      name: "Arabic",
      atomicMass: 39.098,
      atomicNumber: 19,
      atomicWeight: [2, 8, 8, 1],
      column: 1,
      row: 4,
    },
    {
      category: CATEGORIES.Devops,
      symbol: "Jen",
      name: "Jenkins",
      atomicMass: 40.078,
      atomicNumber: 20,
      atomicWeight: [2, 8, 8, 2],
      column: 2,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Bo",
      name: "Big-O Notion",
      atomicMass: 44.956,
      atomicNumber: 21,
      atomicWeight: [2, 8, 9, 2],
      column: 3,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Ad",
      name: "Algorithm Design",
      atomicMass: 47.867,
      atomicNumber: 22,
      atomicWeight: [2, 8, 10, 2],
      column: 4,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Ds",
      name: "Data Structures",
      atomicMass: 50.942,
      atomicNumber: 23,
      atomicWeight: [2, 8, 11, 2],
      column: 5,
      row: 4,
    },
    {
      category: CATEGORIES.Monitoring,
      symbol: "Zb",
      name: "Zabbix",
      atomicMass: 51.996,
      atomicNumber: 24,
      atomicWeight: [2, 8, 13, 1],
      column: 6,
      row: 4,
    },
    {
      category: CATEGORIES.Monitoring,
      symbol: "Po",
      name: "Portainer",
      atomicMass: 54.938,
      atomicNumber: 25,
      atomicWeight: [2, 8, 13, 2],
      column: 7,
      row: 4,
    },
    {
      category: CATEGORIES.Monitoring,
      symbol: "Gr",
      name: "Grafana",
      atomicMass: 55.845,
      atomicNumber: 26,
      atomicWeight: [2, 8, 14, 2],
      column: 8,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Oo",
      name: "Oriented Object",
      atomicMass: 58.933,
      atomicNumber: 27,
      atomicWeight: [2, 8, 15, 2],
      column: 9,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Eb",
      name: "Encryption Basics",
      atomicMass: 58.693,
      atomicNumber: 28,
      atomicWeight: [2, 8, 16, 2],
      column: 10,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Np",
      name: "Network Protocols",
      atomicMass: 63.546,
      atomicNumber: 29,
      atomicWeight: [2, 8, 18, 1],
      column: 11,
      row: 4,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Gt",
      name: "Game Theory",
      atomicMass: 65.38,
      atomicNumber: 30,
      atomicWeight: [2, 8, 18, 2],
      column: 12,
      row: 4,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Ga",
      name: "Gallium",
      atomicMass: 69.723,
      atomicNumber: 31,
      atomicWeight: [2, 8, 18, 3],
      column: 13,
      row: 4,
    },
    {
      category: CATEGORIES.Management,
      symbol: "Pmb",
      name: "Project Management Basics",
      atomicMass: 72.63,
      atomicNumber: 32,
      atomicWeight: [2, 8, 18, 4],
      column: 14,
      row: 4,
    },
    {
      category: CATEGORIES.Management,
      symbol: "Es",
      name: "Estimations",
      atomicMass: 74.922,
      atomicNumber: 33,
      atomicWeight: [2, 8, 18, 5],
      column: 15,
      row: 4,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "S",
      name: "Symfony4",
      atomicMass: 78.971,
      atomicNumber: 34,
      atomicWeight: [2, 8, 18, 6],
      column: 16,
      row: 4,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "H",
      name: "Hibernate",
      atomicMass: 79.904,
      atomicNumber: 35,
      atomicWeight: [2, 8, 18, 7],
      column: 17,
      row: 4,
    },
    {
      category: CATEGORIES.DataBase,
      symbol: "N4J",
      name: "Neo4j",
      atomicMass: 83.798,
      atomicNumber: 36,
      atomicWeight: [2, 8, 18, 8],
      column: 18,
      row: 4,
    },
    {
      category: CATEGORIES.Language,
      symbol: "Sp",
      name: "Spanish",
      atomicMass: 85.468,
      atomicNumber: 37,
      atomicWeight: [2, 8, 18, 8, 1],
      column: 1,
      row: 5,
    },
    {
      category: CATEGORIES.Devops,
      symbol: "Ng",
      name: "Nginx",
      atomicMass: 87.62,
      atomicNumber: 38,
      atomicWeight: [2, 8, 18, 8, 2],
      column: 2,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Ss",
      name: "Software Security Basics",
      atomicMass: 88.906,
      atomicNumber: 39,
      atomicWeight: [2, 8, 18, 9, 2],
      column: 3,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Sd",
      name: "Software Development Process",
      atomicMass: 91.224,
      atomicNumber: 40,
      atomicWeight: [2, 8, 18, 10, 2],
      column: 4,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Rb",
      name: "Robotic Basics",
      atomicMass: 92.906,
      atomicNumber: 41,
      atomicWeight: [2, 8, 18, 12, 1],
      column: 5,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Pc",
      name: "Parallel Computing Basics",
      atomicMass: 95.95,
      atomicNumber: 42,
      atomicWeight: [2, 8, 18, 13, 1],
      column: 6,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Dp",
      name: "Dynamic Programming",
      atomicMass: 98,
      atomicNumber: 43,
      atomicWeight: [2, 8, 18, 13, 2],
      column: 7,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "M",
      name: "Modeling",
      atomicMass: 101.07,
      atomicNumber: 44,
      atomicWeight: [2, 8, 18, 15, 1],
      column: 8,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Or",
      name: "Operational research",
      atomicMass: 102.91,
      atomicNumber: 45,
      atomicWeight: [2, 8, 18, 16, 1],
      column: 9,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Ch",
      name: "Combinatorial and heuristic",
      atomicMass: 106.42,
      atomicNumber: 46,
      atomicWeight: [2, 8, 18, 18],
      column: 10,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "Si",
      name: "Simplex",
      atomicMass: 107.87,
      atomicNumber: 47,
      atomicWeight: [2, 8, 18, 18, 1],
      column: 11,
      row: 5,
    },
    {
      category: CATEGORIES.Basics,
      symbol: "U",
      name: "UML",
      atomicMass: 112.41,
      atomicNumber: 48,
      atomicWeight: [2, 8, 18, 18, 2],
      column: 12,
      row: 5,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "In",
      name: "Indium",
      atomicMass: 114.82,
      atomicNumber: 49,
      atomicWeight: [2, 8, 18, 18, 3],
      column: 13,
      row: 5,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Sn",
      name: "Tin",
      atomicMass: 204.38,
      atomicNumber: 50,
      atomicWeight: [2, 8, 18, 18, 4],
      column: 14,
      row: 5,
    },
    {
      category: CATEGORIES.Management,
      symbol: "Ma",
      name: "Measurements Of Activities",
      atomicMass: 121.76,
      atomicNumber: 51,
      atomicWeight: [2, 8, 18, 18, 5],
      column: 15,
      row: 5,
    },
    {
      category: CATEGORIES.Management,
      symbol: "Pr",
      name: "Project Contronlling",
      atomicMass: 127.6,
      atomicNumber: 52,
      atomicWeight: [2, 8, 18, 18, 6],
      column: 16,
      row: 5,
    },
    {
      category: CATEGORIES.Framework,
      symbol: "V",
      name: "Vue.Js",
      atomicMass: 126.9,
      atomicNumber: 53,
      atomicWeight: [2, 8, 18, 18, 7],
      column: 17,
      row: 5,
    },
    {
      category: CATEGORIES.DataBase,
      symbol: "F",
      name: "Firebase",
      atomicMass: 131.29,
      atomicNumber: 54,
      atomicWeight: [2, 8, 18, 18, 8],
      column: 18,
      row: 5,
    },
    {
      category: CATEGORIES.Language,
      symbol: "Az",
      name: "Amazigh",
      atomicMass: 132.91,
      atomicNumber: 55,
      atomicWeight: [2, 8, 18, 18, 8, 1],
      column: 1,
      row: 6,
    },
    {
      category: CATEGORIES.Devops,
      symbol: "Sh",
      name: "Six Hats Thinking",
      atomicMass: 137.33,
      atomicNumber: 56,
      atomicWeight: [2, 8, 18, 18, 8, 2],
      column: 2,
      row: 6,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Sc",
      name: "Scrum",
      atomicMass: 138.91,
      atomicNumber: 57,
      atomicWeight: [2, 8, 18, 18, 9, 2],
      column: 4,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Ka",
      name: "Kanban",
      atomicMass: 140.12,
      atomicNumber: 58,
      atomicWeight: [2, 8, 18, 19, 9, 2],
      column: 5,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Ap",
      name: "Agile Planning",
      atomicMass: 140.91,
      atomicNumber: 59,
      atomicWeight: [2, 8, 18, 21, 8, 2],
      column: 6,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Pp",
      name: "Pair Programming",
      atomicMass: 144.24,
      atomicNumber: 60,
      atomicWeight: [2, 8, 18, 22, 8, 2],
      column: 7,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Td",
      name: "Test Driven Development",
      atomicMass: 144.24,
      atomicNumber: 61,
      atomicWeight: [2, 8, 18, 23, 8, 2],
      column: 8,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Ci",
      name: "Continuous Integration",
      atomicMass: 150.36,
      atomicNumber: 62,
      atomicWeight: [2, 8, 18, 24, 8, 2],
      column: 9,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Cd",
      name: "Continuous Delivery",
      atomicMass: 151.96,
      atomicNumber: 63,
      atomicWeight: [2, 8, 18, 25, 8, 2],
      column: 10,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Us",
      name: "User Stories",
      atomicMass: 157.25,
      atomicNumber: 64,
      atomicWeight: [2, 8, 18, 25, 9, 2],
      column: 11,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Bm",
      name: "Backlog management",
      atomicMass: 158.93,
      atomicNumber: 65,
      atomicWeight: [2, 8, 18, 27, 8, 2],
      column: 12,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Ut",
      name: "Unit Test",
      atomicMass: 162.5,
      atomicNumber: 66,
      atomicWeight: [2, 8, 18, 28, 8, 2],
      column: 13,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Ft",
      name: "Functional Test",
      atomicMass: 164.93,
      atomicNumber: 67,
      atomicWeight: [2, 8, 18, 29, 8, 2],
      column: 14,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "It",
      name: "Integration Test",
      atomicMass: 167.26,
      atomicNumber: 68,
      atomicWeight: [2, 8, 18, 30, 8, 2],
      column: 15,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "Pt",
      name: "Performance Test",
      atomicMass: 168.93,
      atomicNumber: 69,
      atomicWeight: [2, 8, 18, 31, 8, 2],
      column: 16,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "St",
      name: "Stress Test",
      atomicMass: 173.05,
      atomicNumber: 70,
      atomicWeight: [2, 8, 18, 32, 8, 2],
      column: 17,
      row: 9,
    },
    {
      category: CATEGORIES.AgileMethod ,
      symbol: "At",
      name: "Acceptance Test",
      atomicMass: 174.97,
      atomicNumber: 71,
      atomicWeight: [2, 8, 18, 32, 9, 2],
      column: 18,
      row: 9,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Lc",
      name: "Life Coach",
      atomicMass: 178.49,
      atomicNumber: 72,
      atomicWeight: [2, 8, 18, 32, 10, 2],
      column: 4,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Cu",
      name: "Curiosity",
      atomicMass: 180.95,
      atomicNumber: 73,
      atomicWeight: [2, 8, 18, 32, 11, 2],
      column: 5,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "R",
      name: "Responsibility",
      atomicMass: 183.84,
      atomicNumber: 74,
      atomicWeight: [2, 8, 18, 32, 12, 2],
      column: 6,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Tm",
      name: "Time Management",
      atomicMass: 186.21,
      atomicNumber: 75,
      atomicWeight: [2, 8, 18, 32, 13, 2],
      column: 7,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Cr",
      name: "Conflict Resolution",
      atomicMass: 190.23,
      atomicNumber: 76,
      atomicWeight: [2, 8, 18, 32, 14, 2],
      column: 8,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Ct",
      name: "Creative Thinking",
      atomicMass: 192.22,
      atomicNumber: 77,
      atomicWeight: [2, 8, 18, 32, 15, 2],
      column: 9,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "C",
      name: "Confidence",
      atomicMass: 195.08,
      atomicNumber: 78,
      atomicWeight: [2, 8, 18, 32, 17, 1],
      column: 10,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "E",
      name: "Empathy",
      atomicMass: 196.97,
      atomicNumber: 79,
      atomicWeight: [2, 8, 18, 32, 18, 1],
      column: 11,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Ne",
      name: "Negotiation",
      atomicMass: 200.59,
      atomicNumber: 80,
      atomicWeight: [2, 8, 18, 32, 18, 2],
      column: 12,
      row: 6,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Tl",
      name: "Thallium",
      atomicMass: 204.38,
      atomicNumber: 81,
      atomicWeight: [2, 8, 18, 32, 18, 3],
      column: 13,
      row: 6,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Pb",
      name: "Lead",
      atomicMass: 207.2,
      atomicNumber: 82,
      atomicWeight: [2, 8, 18, 32, 18, 4],
      column: 14,
      row: 6,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Bi",
      name: "Bismuth",
      atomicMass: 208.98,
      atomicNumber: 83,
      atomicWeight: [2, 8, 18, 32, 18, 5],
      column: 15,
      row: 6,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "Po",
      name: "Polonium",
      atomicMass: 209,
      atomicNumber: 84,
      atomicWeight: [2, 8, 18, 32, 18, 6],
      column: 16,
      row: 6,
    },
    {
      category: CATEGORIES.Management,
      symbol: "At",
      name: "Astatine",
      atomicMass: 210,
      atomicNumber: 85,
      atomicWeight: [2, 8, 18, 32, 18, 7],
      column: 17,
      row: 6,
    },
    {
      category: CATEGORIES.DataBase,
      symbol: "M",
      name: "MongoDB",
      atomicMass: 222,
      atomicNumber: 86,
      atomicWeight: [2, 8, 18, 32, 18, 8],
      column: 18,
      row: 6,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "I",
      name: "Innovation",
      atomicMass: 223,
      atomicNumber: 87,
      atomicWeight: [2, 8, 18, 32, 18, 8, 1],
      column: 1,
      row: 7,
    },
    {
      category: CATEGORIES.Devops,
      symbol: "Re",
      name: "Reverse Engineering",
      atomicMass: 226,
      atomicNumber: 88,
      atomicWeight: [2, 8, 18, 32, 18, 8, 2],
      column: 2,
      row: 7,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Ap",
      name: "Architecture Pattern",
      atomicMass: 227,
      atomicNumber: 89,
      atomicWeight: [2, 8, 18, 32, 18, 9, 2],
      column: 4,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Dd",
      name: "Database design",
      atomicMass: 232.04,
      atomicNumber: 90,
      atomicWeight: [2, 8, 18, 32, 18, 10, 2],
      column: 5,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Cd",
      name: "Component Design",
      atomicMass: 231.04,
      atomicNumber: 91,
      atomicWeight: [2, 8, 18, 32, 20, 9, 2],
      column: 6,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Re",
      name: "Re-Engineering",
      atomicMass: 238.03,
      atomicNumber: 92,
      atomicWeight: [2, 8, 18, 32, 21, 9, 2],
      column: 7,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Re",
      name: "Reverse Engineering",
      atomicMass: 237,
      atomicNumber: 93,
      atomicWeight: [2, 8, 18, 32, 22, 9, 2],
      column: 8,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "UI",
      name: "User Interface",
      atomicMass: 244,
      atomicNumber: 94,
      atomicWeight: [2, 8, 18, 32, 24, 8, 2],
      column: 9,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "UX",
      name: "User Experience",
      atomicMass: 243,
      atomicNumber: 95,
      atomicWeight: [2, 8, 18, 32, 25, 8, 2],
      column: 10,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Cm",
      name: "Curium",
      atomicMass: 247,
      atomicNumber: 96,
      atomicWeight: [2, 8, 18, 32, 25, 9, 2],
      column: 11,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Bk",
      name: "Berkelium",
      atomicMass: 247,
      atomicNumber: 97,
      atomicWeight: [2, 8, 18, 32, 27, 8, 2],
      column: 12,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Cf",
      name: "Californium",
      atomicMass: 251,
      atomicNumber: 98,
      atomicWeight: [2, 8, 18, 32, 28, 8, 2],
      column: 13,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Es",
      name: "Einsteinium",
      atomicMass: 252,
      atomicNumber: 99,
      atomicWeight: [2, 8, 18, 32, 29, 8, 2],
      column: 14,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Fm",
      name: "Fermium",
      atomicMass: 257,
      atomicNumber: 100,
      atomicWeight: [2, 8, 18, 32, 30, 8, 2],
      column: 15,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Md",
      name: "Mendelevium",
      atomicMass: 258,
      atomicNumber: 101,
      atomicWeight: [2, 8, 18, 32, 31, 8, 2],
      column: 16,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "No",
      name: "Nobelium",
      atomicMass: 259,
      atomicNumber: 102,
      atomicWeight: [2, 8, 18, 32, 32, 8, 2],
      column: 17,
      row: 10,
    },
    {
      category: CATEGORIES.Design,
      symbol: "Lr",
      name: "Lawrencium",
      atomicMass: 266,
      atomicNumber: 103,
      atomicWeight: [2, 8, 18, 32, 32, 8, 3],
      column: 18,
      row: 10,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Ei",
      name: "Emotional Intelligence",
      atomicMass: 267,
      atomicNumber: 104,
      atomicWeight: [2, 8, 18, 32, 32, 10, 2],
      column: 4,
      row: 7,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "O",
      name: "Organization",
      atomicMass: 268,
      atomicNumber: 105,
      atomicWeight: [2, 8, 18, 32, 32, 11, 2],
      column: 5,
      row: 7,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "C",
      name: "Creativity",
      atomicMass: 269,
      atomicNumber: 106,
      atomicWeight: [2, 8, 18, 32, 32, 12, 2],
      column: 6,
      row: 7,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Cs",
      name: "Communication Skills",
      atomicMass: 270,
      atomicNumber: 107,
      atomicWeight: [2, 8, 18, 32, 32, 13, 2],
      column: 7,
      row: 7,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Sm",
      name: "Stress Management",
      atomicMass: 277,
      atomicNumber: 108,
      atomicWeight: [2, 8, 18, 32, 32, 14, 2],
      column: 8,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "C",
      name: "C",
      atomicMass: 278,
      atomicNumber: 109,
      atomicWeight: [2, 8, 18, 32, 32, 15, 2],
      column: 9,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "JAVA",
      name: "JAVA",
      atomicMass: 281,
      atomicNumber: 110,
      atomicWeight: [2, 8, 18, 32, 32, 17, 1],
      column: 10,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "Js",
      name: "JavaScript",
      atomicMass: 282,
      atomicNumber: 111,
      atomicWeight: [2, 8, 18, 32, 32, 17, 2],
      column: 11,
      row: 7,
    },
    {
      category: CATEGORIES.SoftSkills,
      symbol: "Ls",
      name: "LeaderShip",
      atomicMass: 282,
      atomicNumber: 112,
      atomicWeight: [2, 8, 18, 32, 32, 18, 2],
      column: 12,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "P",
      name: "Python",
      atomicMass: 286,
      atomicNumber: 113,
      atomicWeight: [2, 8, 18, 32, 32, 18, 3],
      column: 13,
      row: 7,
    },
    {
      category: CATEGORIES.PostSoftSkills,
      symbol: "De",
      name: "Dart",
      atomicMass: 289,
      atomicNumber: 114,
      atomicWeight: [2, 8, 18, 32, 32, 18, 4],
      column: 14,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "PHP",
      name: "PHP",
      atomicMass: 290,
      atomicNumber: 115,
      atomicWeight: [2, 8, 18, 32, 32, 18, 5],
      column: 15,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "D",
      name: "Dart",
      atomicMass: 293,
      atomicNumber: 116,
      atomicWeight: [2, 8, 18, 32, 32, 18, 6],
      column: 16,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "HTML",
      name: "HTML",
      atomicMass: 294,
      atomicNumber: 117,
      atomicWeight: [2, 8, 18, 32, 32, 18, 7],
      column: 17,
      row: 7,
    },
    {
      category: CATEGORIES.ProgrammingLanguage,
      symbol: "CSS",
      name: "CSS",
      atomicMass: 294,
      atomicNumber: 118,
      atomicWeight: [2, 8, 18, 32, 32, 18, 8],
      column: 18,
      row: 7,
    },
  ];

  return (
    <section className="skills" id="skills">
      <h2 className="heading">
        <i className="fas fa-laptop-code" /> Skills &amp; <span>Abilities</span>
      </h2>
      <div className="wrapper">
        {Object.keys(CATEGORIES).map((key) => {
          return (
            <Fragment>
              <input
                className="category-toggle"
                type="radio"
                id={
                  CATEGORIES[key] != "unknown"
                    ? `${CATEGORIES[key]}s`
                    : `${CATEGORIES[key]}`
                }
                name="categories"
              />
              <input
                className="category-cancel"
                type="radio"
                id="cancel"
                name="categories"
              />
            </Fragment>
          );
        })}

        <div className="periodic-table">
          {ELEMENTS.map((element) => {
            return (
              <AtomicElement
                category={element.category}
                symbol={element.symbol}
                name={element.name}
                atomicMass={element.atomicMass}
                atomicNumber={element.atomicNumber}
                atomicWeight={element.atomicWeight}
                column={element.column}
                row={element.row}
              />
            );
          })}

          <div className="element lanthanoid c3 r6">
            <div className="square">57-71</div>
          </div>
          <div className="element actinoid c3 r7">
            <div className="square">89-103</div>
          </div>
          <div className="gap c3 r8" />
          <div className="key">
            <div className="row">
              {Object.keys(CATEGORIES).map((key) => {
                return (
                  <label
                    className={CATEGORIES[key]}
                    htmlFor={
                      CATEGORIES[key] != "unknown"
                        ? `${CATEGORIES[key]}s`
                        : `${CATEGORIES[key]}`
                    }
                  >
                    {key.replace(/[A-Z]/g, (letter) => ` ${letter}`)}
                  </label>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Periodic;
